[package]
name = "app"
version = "0.1.0"
edition = "2024"
categories = [
  "command-line-utilities",
  "config",
  "development-tools",
  "development-tools::cargo-plugins",
  "parsing",
]

[dependencies]
