name: Debug
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  check:
    name: Multi Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cargo Get
        id: metadata
        uses: nicolaiunrein/cargo-get@master

      - name: Check variables
        run: |
          echo "Package Name"
          echo "${{ steps.metadata.outputs.package_name}}"
          echo "-----------------------------------------"

          echo "Package Version"
          echo "${{ steps.metadata.outputs.package_version}}"
          echo "-----------------------------------------"

          echo "Package Categories"
          echo "${{ steps.metadata.outputs.package_categories}}"
          echo "-----------------------------------------"

          echo "Package Keywords"
          echo "${{ steps.metadata.outputs.package_keywords}}"
          echo "-----------------------------------------"
