name: Debug
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  check:
    name: Multi Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cargo Get
        id: cargo-get
        run: |
          cargo install cargo-get --git https://github.com/nicolaiunrein/cargo-get --branch "feat/all-values"

      - name: Manual run
        id: metadata
        run: |
          "$(cargo get all --output-format github-action)" >> $GITHUB_OUTPUT

      - name: Check variables
        run: |
          echo "Package Name"
          echo "${{ steps.metadata.outputs.package_name}}"
          echo "-----------------------------------------"

          echo "Package Version"
          echo "${{ steps.metadata.outputs.package_version}}"
          echo "-----------------------------------------"

          echo "Package Keywords"
          echo "${{ steps.metadata.outputs.package_keywords}}"
          echo "-----------------------------------------"
