name: Debug
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  check:
    name: Multi Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cargo Get
        id: cargo-get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.name

      - name: Manual run
        id: metadata
        run: |
          multiline=$'my_var=hello\nworld\nmy_var_2=test'
          echo "$multiline" >> $GITHUB_OUTPUT

      - name: Check variables
        run: |
          echo "${{ steps.metadata.outputs.my_var}}"
          echo "-----------------------------------------"
          echo "${{ steps.metadata.outputs.my_var_2}}"
