name: Debug
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  check:
    name: Multi Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cargo Get
        id: cargo-get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.name

      - name: Manual run
        id: metadata
        run: |
          echo "package_name<<<EOFcargo-getEOF
          package_edition<<<EOF2018EOF
          package_version<<<EOF1.3.0EOF
          package_authors<<<EOFNicolai Unrein <n.unrein@gmail.com>EOF
          package_description<<<EOFCargo plugin to easily query information from Cargo.toml filesEOF
          package_readme<<<EOFREADME.mdEOF
          package_keywords<<<EOFbinary
          cargo
          cli
          dev-tools
          queryEOF
          package_categories<<<EOFcommand-line-utilities
          config
          development-tools
          development-tools::cargo-plugins
          parsingEOF
          package_exclude<<<EOFEOF
          package_include<<<EOFsrc/**/*
          README.mdEOF
          package_license<<<EOFApache-2.0/MITEOF
          package_repository<<<EOFhttps://github.com/nicolaiunrein/cargo-getEOF
          package_publish<<<EOFtrueEOF" >> $GITHUB_OUTPUT

      - name: Check variables
        run: |
          echo "Package Name"
          echo "${{ steps.metadata.outputs.package_name}}"
          echo "-----------------------------------------"

          echo "Package Version"
          echo "${{ steps.metadata.outputs.package_version}}"
          echo "-----------------------------------------"

          echo "Package Keywords"
          echo "${{ steps.metadata.outputs.package_keywords}}"
          echo "-----------------------------------------"
