name: Debug
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  check:
    name: Multi Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cargo Get
        id: cargo-get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.name

      - name: Manual run
        id: metadata
        run: |
          echo 'my_var<<EOF' >> $GITHUB_OUTPUT
          echo "val1" >> $GITHUB_OUTPUT
          echo "val2" >> $GITHUB_OUTPUT
          echo "val3" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          # echo "my_var_2=test" >> $GITHUB_OUTPUT

      - name: Check variables
        run: |
          echo "${{ steps.metadata.outputs.my_var}}"
          echo "-----------------------------------------"
          # echo "${{ steps.metadata.outputs.my_var_2}}"
